library(SingleCellExperiment)
library(TSCAN)
library(M3Drop)
library(monocle)
library(monocle3)
library(destiny)
library(scater)
library(ggplot2)
library(ggthemes)
library(ggbeeswarm)
library(corrplot)
library(Polychrome)
library(slingshot)
library(SLICER)
library("lle")
#library(ouija)
set.seed(1)



